#!/usr/bin/env bash
# Installs and configures Nginx web server on Ubuntu

# Install nginx
apt-get update
apt-get install -y nginx

# Start nginx
service nginx start

# Configure nginx to listen on port 80
sed -i 's/^listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Create a temporary HTML file
echo "Hello World!" > /usr/share/nginx/html/index.html

# Restart nginx
service nginx restart
