#!/usr/bin/env bash
# Configure Nginx server to redirect /redirect_me to another page

# Install Nginx
apt-get update
apt-get -y install nginx

# Create a configuration file for redirection
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}" > /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the site
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove default Nginx configuration
rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
service nginx restart
