#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

# Install Nginx
apt-get update
apt-get -y install nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Create a configuration file for custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}" > /etc/nginx/sites-available/custom_404

# Create a symbolic link to enable the site
ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Remove default Nginx configuration
rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
service nginx restart
