#!/usr/bin/env bash

# Display header
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Display process information
ps aux | awk '{printf("%-10s %-4d %-3.1f %-4.1f %-5d %-4d %-8s %-4s %-5s %-10s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10)}'
