#!/usr/bin/env bash

# Find the PID of the process named '7-highlander'
pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -n "$pid" ]; then
    # Kill the process
    kill "$pid"
    echo "Killed"
else
    echo "Process '7-highlander' not found."
fi
