#!/usr/bin/env bash

# Display the story of /etc/passwd using while loop + IFS

while IFS=: read -r user x uid gid name home shell; do
    echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $x, more info about the user here: $name"
done < /etc/passwd
