#!/usr/bin/env bash

# Group visitors by IP and HTTP status code, display occurrence number, and sort data

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $2, $3, $1}'
